In [34]:
import numpy as np
import random


- Que se muestren todas las minas al perder
- Agregar banderitas
- Expander el espacio de los vecinos

In [35]:
mina = "*"
no_pulsado = "."
pulsado = "-"
tablero_ini = []
WIN = False
GAME_OVER = False

In [36]:
def CreaTablero():
    global tablero_ini
    global nf
    global nc
    tablero_ini = []
    nf = 10
    nc = 8
    nm = 8
    # Matriz pulsado
    # rellenar matriz de 0 
    p = np.zeros((nf, nc))
    
    # Tablero inicial
    for fila in range(nf):
        tablero_ini.append([])
        for columna in range(nc):
                tablero_ini[fila].append(no_pulsado)
    
    
    
    # Matriz mina
    m = np.zeros((nf, nc))
    M2 = np.zeros((nf+2, nc+2))
    # Num minas
    a = np.zeros((nf, nc))
    # Pos de las minas
    pos = []
    for i in range(nm):
        f = random.randint(0, nf-1)
        c = random.randint(0, nc-1)
        m[f,c] = 1 
        M2[f+1,c+1] = 1 
        pos.append(tuple([f,c]))
        #pos.append(np.array(f,c))
    return(p,m,a,M2,tablero_ini)
    
ct = CreaTablero()
p  = ct[0]
m = ct[1]
a = ct[2]
M2 = ct[3]
tablero_inicial = ct[4]

In [37]:
print("m \n",m)

m 
 [[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [38]:
print("M2 \n",M2)

M2 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [39]:
# Recorro filas
for i in range(1,M2.shape[0]-1): # Recorro de la 1 a la 10
    # Recorro cols
    for j in range(1,M2.shape[1]-1):
        cont  = 0
        print('Posición: ',i,j)
        print('P1, arriba izq',M2[i-1,j-1])
        if M2[i-1,j-1] == 1 :
            cont +=1
        print('P2, arriba',M2[i-1,j])
        if M2[i-1,j] == 1:
            cont +=1
        print('P3, arriba der',M2[i-1,j+1])
        if M2[i-1,j+1] == 1:
            cont +=1
        print('P4,  izq', M2[i,j-1])
        if  M2[i,j-1] == 1:
            cont +=1
        print('P5, der ',M2[i,j+1])
        if M2[i,j+1] == 1:
            cont += 1
        print('P6, abajo izq',M2[i+1,j-1] )
        if M2[i+1,j-1] == 1:
            cont +=1
        print('P7, abajo',M2[i+1,j])
        if M2[i+1,j] == 1:
            cont +=1
        print('P8, abajo der',M2[i+1,j+1])
        if M2[i+1,j+1] == 1:
            cont +=1
        print("Contador para la posición: ",str(cont))

Posición:  1 1
P1, arriba izq 0.0
P2, arriba 0.0
P3, arriba der 0.0
P4,  izq 0.0
P5, der  1.0
P6, abajo izq 0.0
P7, abajo 0.0
P8, abajo der 0.0
Contador para la posición:  1
Posición:  1 2
P1, arriba izq 0.0
P2, arriba 0.0
P3, arriba der 0.0
P4,  izq 0.0
P5, der  0.0
P6, abajo izq 0.0
P7, abajo 0.0
P8, abajo der 0.0
Contador para la posición:  0
Posición:  1 3
P1, arriba izq 0.0
P2, arriba 0.0
P3, arriba der 0.0
P4,  izq 1.0
P5, der  0.0
P6, abajo izq 0.0
P7, abajo 0.0
P8, abajo der 0.0
Contador para la posición:  1
Posición:  1 4
P1, arriba izq 0.0
P2, arriba 0.0
P3, arriba der 0.0
P4,  izq 0.0
P5, der  0.0
P6, abajo izq 0.0
P7, abajo 0.0
P8, abajo der 0.0
Contador para la posición:  0
Posición:  1 5
P1, arriba izq 0.0
P2, arriba 0.0
P3, arriba der 0.0
P4,  izq 0.0
P5, der  0.0
P6, abajo izq 0.0
P7, abajo 0.0
P8, abajo der 1.0
Contador para la posición:  1
Posición:  1 6
P1, arriba izq 0.0
P2, arriba 0.0
P3, arriba der 0.0
P4,  izq 0.0
P5, der  0.0
P6, abajo izq 0.0
P7, abajo 1.0
P8, 

In [40]:

# Recorro filas
for i in range(1,M2.shape[0]-1): # Recorro de la 1 a la 10
    # Recorro cols
    for j in range(1,M2.shape[1]-1): # Recorro de la 1 a la 8
        cont = 0 
        if M2[i-1,j-1] == 1: # Pos1
            cont +=1
        if M2[i-1,j] == 1: # Pos2
            cont +=1
        if M2[i-1,j+1] == 1: # Pos3 
            cont +=1
        if M2[i,j-1] == 1: # Pos4
            cont +=1
        if M2[i,j+1] == 1: # Pos5
            cont +=1
        if M2[i+1,j-1] == 1: # Pos 6
            cont +=1
        if M2[i+1,j] == 1: # Pos 7
            cont +=1
        if M2[i+1,j+1] == 1: # Pos 7
            cont +=1
        if M2[i,j] :
            pass
        a[i-1,j-1] = cont
        #print("Hay "+str(cont)+" minas alrededor de la posición "+str(i)+','+str(j))

In [41]:
print("a: \n",a)

a: 
 [[1. 0. 1. 0. 1. 1. 1. 0.]
 [1. 1. 1. 0. 1. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 2. 1. 1. 0. 0.]
 [0. 1. 1. 2. 1. 2. 1. 0.]
 [0. 0. 0. 1. 2. 1. 1. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0.]
 [1. 2. 1. 1. 0. 1. 1. 1.]
 [0. 2. 0. 1. 0. 1. 0. 1.]
 [1. 2. 1. 1. 0. 1. 1. 1.]]


In [42]:
print("m: \n",m)

m: 
 [[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [43]:
print("p: \n",p)

p: 
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [51]:
m[0,1]

1.0

In [56]:
print("Comienzo del juego")

for i in tablero_inicial:
    print(np.array(i))





Comienzo del juego
['.' '*' '.' '.' '.' '.' '.' '.']
['.' '*' '.' '.' '.' '.' '.' '.']
['.' '*' '.' '.' '.' '.' '.' '.']
['.' '*' '.' '.' '.' '.' '.' '.']
['.' '*' '.' '.' '.' '.' '.' '.']
['.' '*' '.' '.' '.' '.' '.' '.']
['.' '*' '.' '.' '.' '.' '.' '.']
['.' '*' '.' '.' '.' '.' '.' '.']
['.' '*' '.' '.' '.' '.' '.' '.']
['.' '*' '.' '.' '.' '.' '.' '.']


In [57]:
p

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:

def movimiento():
    '''
    Función que pide una fila y col para hacer movimiento
    '''
    global fila
    global col 
    # Selección de fila
    while True:
        try:
            fila = int(input("Indique la fila: "))
            fila = fila-1 # Resto 1 por los índices en python
            if  fila < 0 or fila > 9:
                raise ValueError
                
            break
        except ValueError:
            print("Introduzca una fila entre 0 y 10")
    # Selección de columna
    while True:
        try:
            col =  int(input("Indique la columna: "))
            col = col-1 # Resto 1 por los índices en python
            if  col < 0 or col > 7 :
                raise ValueError
                
            break
        except ValueError:
            print("Introduzca una columna entre 0 y 8")


#movimiento() # Inicio juego


In [ ]:
# mina = "*"
# no_pulsado = "."
# pulsado = "-"
# tablero_ini = []
# WIN = False
# GAME_OVER = False

In [ ]:
while not GAME_OVER: # Mientras que no hayamos perdido
    print("Movimiento: ", str(fila+1),',',str(col+1))
    if p[fila,col] != 0 :
        print('Esa casilla ya ha sido pulsada, pruebe de nuevo: ')
        movimiento()
        print("-"*20)
    elif m[fila,col] == 1:
        print("Ha perdido, había una mina")
        tablero_inicial[fila][col] = mina
        GAME_OVER = True
        print('Tablero de juego: \n 1 2 3 4 5 6 7 8')

        for i in tablero_ini: 
            for j in range(nf):
                if j == 0:
                    print('')
                    print(i)
                else: 

                    print(j,'-',i)
        break
    else:
        p[fila,col] = 1 # Modifico p 
        if a[fila,col] != 0: # Es decir, que tiene o mina o nº
            tablero_inicial[fila][col]  = int(a[fila,col])
        if a[fila,col] == 0:
            tablero_inicial[fila][col] = pulsado # Tablero ini es una lista
        print('Tablero de juego: \n')
        for i in tablero_ini: 
            print(i)
        print("-"*20)
        movimiento()
         


NameError: name 'fila' is not defined